Initial working implementation of PUT

diff --git a/test/https/Justfile b/test/https/Justfile
--- a/test/https/Justfile
+++ b/test/https/Justfile
@@ -15,7 +15,7 @@ push:
     docker push {{docker_image}}
 
 
-test: _start && _stop
+test: _start #&& _stop
     #!/bin/bash
     cat <<'EOF' > common.sh
     #!/bin/bash
@@ -71,6 +71,16 @@ _test_ship_get_binary_file:
     source common.sh
     sha_input=$(sha256sum binary_file.tar.gz | cut -d' ' -f1)
     ship http://localhost:8081/test_binary.file -s -o downloaded_test_binary.file
+    sha_output=$(sha256sum downloaded_test_binary.file | cut -d' ' -f1)
+    [ "$sha_input" = "$sha_output" ] && ok || err "ERROR: input and output SHA256s don't match."
+    rm downloaded_test_binary.file
+
+_test_ship_put_binary_file:
+    #!/bin/bash
+    source common.sh
+    sha_input=$(sha256sum binary_file.tar.gz | cut -d' ' -f1)
+    ship binary_file.tar.gz -o http://localhost:8081/uploaded_binary.file
+    #ship http://localhost:8081/test_binary.file -s -o downloaded_test_binary.file
     sha_output=$(sha256sum downloaded_test_binary.file | cut -d' ' -f1)
     [ "$sha_input" = "$sha_output" ] && ok || err "ERROR: input and output SHA256s don't match."
     rm downloaded_test_binary.file
