Add optional SHA256 check of downloads

diff --git a/test/ftp/Justfile b/test/ftp/Justfile
--- a/test/ftp/Justfile
+++ b/test/ftp/Justfile
@@ -71,3 +71,19 @@ _test_curl_login:
     source common.sh
     response=$(curl -s -w "%{http_code}" "ftp://localhost:21/" --user "user:pass")
     [ $response = "226" ] && ok || "ERROR: Response code $response."
+
+_test_aim_checksum_works:
+    #!/bin/bash
+    source common.sh
+    sha_expected="1fda8bdf225ba614ce1e7db8830e4a2e9ee55907699521d500b1b7beff18523b"
+    aim -s ftp://ftp.fau.de:21/gnu/MailingListArchives/README _test_aim_checksum_works $sha_expected
+    [ $? -eq 0 ] && ok || err "ERROR: expected and actual SHA256s don't match."
+    rm _test_aim_checksum_works
+
+_test_aim_checksum_fails_when_checksum_mismatch:
+    #!/bin/bash
+    source common.sh
+    sha_expected="AAAA0d7139c8c7e3ff20cb243e94bc5993517d88e8be8d59129730607d5c631b"
+    aim -s ftp://ftp.fau.de:21/gnu/MailingListArchives/README _test_aim_checksum_fails_when_checksum_mismatch $sha_expected
+    [ $? -ne 0 ] && ok || err "ERROR: expected checksum mismatch, got equal."
+    rm _test_aim_checksum_fails_when_checksum_mismatch
diff --git a/test/https/Justfile b/test/https/Justfile
--- a/test/https/Justfile
+++ b/test/https/Justfile
@@ -96,3 +96,19 @@ _test_aim_put_resume_binary_file:
     sha_output=$(sha256sum _test_aim_put_resume_binary_file | cut -d' ' -f1)
     [ "$sha_input" = "$sha_output" ] && ok || ok "ERROR: input and output SHA256s don't match."
     rm _test_aim_put_resume_binary_file
+
+_test_aim_checksum_works:
+    #!/bin/bash
+    source common.sh
+    sha_expected="0e0f0d7139c8c7e3ff20cb243e94bc5993517d88e8be8d59129730607d5c631b"
+    aim -s https://github.com/XAMPPRocky/tokei/releases/download/v12.0.4/tokei-x86_64-unknown-linux-gnu.tar.gz _test_aim_checksum_works $sha_expected
+    [ $? -eq 0 ] && ok || err "ERROR: expected and actual SHA256s don't match."
+    rm _test_aim_checksum_works
+
+_test_aim_checksum_fails_when_checksum_mismatch:
+    #!/bin/bash
+    source common.sh
+    sha_expected="AAAA0d7139c8c7e3ff20cb243e94bc5993517d88e8be8d59129730607d5c631b"
+    aim -s https://github.com/XAMPPRocky/tokei/releases/download/v12.0.4/tokei-x86_64-unknown-linux-gnu.tar.gz _test_aim_checksum_fails_when_checksum_mismatch $sha_expected
+    [ $? -ne 0 ] && ok || err "ERROR: expected checksum mismatch, got equal."
+    rm _test_aim_checksum_fails_when_checksum_mismatch
