Add ssh get automated test

diff --git a/test/ssh/Justfile b/test/ssh/Justfile
--- a/test/ssh/Justfile
+++ b/test/ssh/Justfile
@@ -18,7 +18,6 @@ setup:
 
 start_ssh_server +docker_compose_args="": setup
     #!/bin/bash
-    echo foobar > /tmp/binfile
     docker-compose --file {{ docker_compose_file }} up {{docker_compose_args}} >/dev/null 2>&1
     max_seconds=30
     for i in 1..$max_seconds; do
@@ -49,3 +48,13 @@ _test_ssh_server_up:
     pass="pass"
     sshpass -p $pass ssh -q -i keys/id_ed25519 -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $user@127.0.0.1 -p 2222 'exit'
     [ $? -eq 0 ] && ok || err "Couldn't connect to local dockerized ssh server."
+
+_test_aim_get:
+    #!/bin/bash
+    test=$(basename $0) && source ../common.sh
+    echo foobar > /tmp/binfile
+    sha_input=$(sha256sum /tmp/binfile | cut -d' ' -f1)
+    aim ssh://user:pass@127.0.0.1:2222/tmp/binfile $test
+    sha_output=$(sha256sum $test | cut -d' ' -f1)
+    [ "$sha_input" = "$sha_output" ] && ok || err "ERROR: input and output SHA256s don't match."
+    rm $test
