Assert Cargo.toml version matches release

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -12,9 +12,33 @@ on:
         description: Manual trigger
 
 jobs:
+  common-assertions:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Cargo version matches tag
+        if: github.event_name == 'push'
+        run: |
+          function ok() {
+            echo -e "\e[1;32mOK\e[0m"
+          }  
+          function err() {
+            echo -e "\e[1;31m${@}\e[0m" >&2
+            exit 1
+          }
+
+          CRATE_VERSION=$(cat Cargo.toml | grep -e "^version" | head -1 | cut -d '=' -f2 | sed -e "s/ //" -e "s/\"//g")
+          [[ $GITHUB_REF == *"refs/tags"* ]] && TAG=$GITHUB_REF || err "Cannot determine git tag."
+          TAG=${TAG/refs\/tags\//}
+          [ "$CRATE_VERSION" = "$TAG" ] && ok "OK" || err "ERROR: Crate version does not match the git (release) tag."  
+
   publish-to-github:
     name: Building ${{ matrix.job.target }}
     runs-on: ${{ matrix.job.os }}
+    needs:
+      - common-assertions
     strategy:
       matrix:
         job:
@@ -79,6 +103,8 @@ jobs:
  
   publish-to-dockerhub:
     runs-on: ubuntu-latest
+    needs:
+      - common-assertions
     steps:
       - name: Checkout
         uses: actions/checkout@v2
